[package]
name = "proxy"
version = "0.1.0"
authors = ["brymko <47984664+brymko@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.6.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = { version = "0.6.1" }


